# vim: ft=yaml.docker-compose

services:
  panelsh-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=development
    restart: always
    volumes:
      - panelsh-data:/data
      - ./:/usr/src/app/

  panelsh-websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    depends_on:
      - panelsh-server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
    restart: always
    volumes:
      - panelsh-data:/data

  panelsh-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - panelsh-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - panelsh-data:/data

  redis:
    platform: "linux/amd64"
    image: redis:alpine

  panelsh-nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 8000:80
    environment:
      - HOME=/data
    depends_on:
      - panelsh-server
      - panelsh-websocket
    restart: always
    volumes:
      - panelsh-data:/data:ro

volumes:
    panelsh-data:
    redis-data:
