# vim: ft=yaml.docker-compose

services:
  panelsh-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENVIRONMENT=test
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - panelsh-data:/data

  panelsh-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - panelsh-test
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: always
    volumes:
      - panelsh-data:/data

  redis:
    image: redis:alpine

volumes:
  panelsh-data:
  redis-data:
