---
- name: Ensure folders exist
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USER') }}/{{ item }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0755"
  with_items:
    - .panelsh
    - .config
    - panelsh_assets

- name: Create empty .asoundrc
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USER') }}/.asoundrc"
    state: touch
    force: false
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "0644"

- name: Copy Panelsh default assets file
  ansible.builtin.copy:
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0644"
    src: default_assets.yml
    dest: "/home/{{ lookup('env', 'USER') }}/.panelsh/default_assets.yml"
    force: true

- name: Remove deprecated parameter "listen"
  ansible.builtin.lineinfile:
    regexp: '^.*listen.*'
    state: absent
    dest: "/home/{{ lookup('env', 'USER') }}/.panelsh/panelsh.conf"

- name: Install pip dependencies
  ansible.builtin.pip:
    executable: "/home/{{ lookup('env', 'USER') }}/installer_venv/bin/pip"
    requirements: "/home/{{ lookup('env', 'USER') }}/panelsh/requirements/requirements.host.txt"
    extra_args: "--no-cache-dir --upgrade"
  when: ansible_distribution_major_version | int >= 12

- name: Install pip dependencies (Debian 11 and older)
  ansible.builtin.pip:
    executable: "/home/{{ lookup('env', 'USER') }}/installer_venv/bin/pip"
    name:
      - ansible-core==2.15.9
      - docker==6.0.0
      - getmac==0.9.4
      - netifaces2==0.0.22
      - redis==4.3.4
      - "requests[security]==2.32.3"
      - tenacity==9.0.0
    extra_args: "--no-cache-dir --upgrade"
  when: ansible_distribution_major_version | int <= 11

- name: Remove panelsh_utils.sh
  ansible.builtin.file:
    state: absent
    path: /usr/local/bin/panelsh_utils.sh

- name: Cron job to cleanup panelsh_assets
  ansible.builtin.cron:
    name: Cleanup panelsh_assets
    state: absent
    user: "{{ lookup('env', 'USER') }}"

- name: Download upgrade script from github repository
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Panelsh/Panelsh/master/bin/install.sh
    dest: /usr/local/sbin/upgrade_panelsh.sh
    mode: "0700"
    owner: root
    group: root
    force: true

- name: Remove the old upgrade script
  ansible.builtin.file:
    state: absent
    path: /usr/local/sbin/upgrade_panelsh.sh
    owner: root
    group: root

- name: Copy panelsh_overrides
  ansible.builtin.copy:
    src: panelsh_overrides
    dest: /etc/sudoers.d/panelsh_overrides
    mode: "0440"
    owner: root
    group: root

- name: Remove /usr/local/bin/panelsh_usb_assets.sh (deprecated)
  ansible.builtin.file:
    state: absent
    path: /usr/local/bin/panelsh_usb_assets.sh
    owner: root
    group: root

- name: Cleans up autoplay udev rule
  ansible.builtin.file:
    state: absent
    path: /etc/udev/rules.d/50-autoplay.rules

- name: Copy panelsh systemd units
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  with_items: "{{ panelsh_systemd_units }}"

- name: Remove plymouth-quit-wait.service
  ansible.builtin.file:
    state: absent
    dest: /lib/systemd/system/plymouth-quit-wait.service

- name: Remove plymouth-quit.service
  ansible.builtin.file:
    state: absent
    dest: /lib/systemd/system/plymouth-quit.service

- name: Enable panelsh systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ panelsh_systemd_units }}"

- name: Check if deprecated systemd services exists
  ansible.builtin.stat:
    path: /etc/systemd/system/X.service
  register: x_service

- name: Set the x_service fact
  ansible.builtin.set_fact:
    x_service_exist: "{{ x_service.stat.exists }}"

- name: Disable deprecated systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ deprecated_panelsh_systemd_units }}"
  when: x_service_exist

- name: Remove deprecated systemd units
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}"
    state: absent
  with_items: "{{ deprecated_panelsh_systemd_units }}"

- name: Remove the ngrok binary
  ansible.builtin.file:
    path: "/usr/local/bin/ngrok"
    state: absent
    owner: root
    group: root
