blank_issues_enabled: false
contact_links:
  - name: Panelsh Website
    url: https://panelsh.panelsh.io
    about: Visit our official website for general information and documentation
  - name: Panelsh Forum
    url: https://forums.panelsh.io
    about: Join our community forum for help, discussions, and sharing experiences
  - name: GitHub Discussions
    url: https://github.com/Panelsh/Panelsh/discussions
    about: For general questions and discussions about Panelsh