assets:
  - name: Panelsh Weather Widget
    uri: https://weather.srly.io
    mimetype: webpage

  - name: Panelsh Clock Widget
    uri: https://clock.srly.io
    mimetype: webpage

  - name: Hacker News
    uri: https://news.ycombinator.com
    mimetype: webpage
