panelsh_systemd_units:
  - panelsh-host-agent.service

deprecated_panelsh_systemd_units:
  - panelsh-celery.service
  - panelsh-web.service
  - panelsh-websocket_server_layer.service
  - panelsh-viewer.service
  - X.service
  - matchbox.service
  - panelsh-host-agent.service
  - udev-restart.service
  - wifi-connect.service
